{
	"version": 1625150299,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/gambaricon-sheet0.png",
		"images/gambaricon-sheet1.png",
		"images/kotak-sheet0.png",
		"images/kembali-sheet0.png",
		"images/level-sheet0.png",
		"images/waktu-sheet0.png",
		"images/spritefont.png",
		"images/huruf_drag-sheet0.png",
		"images/huruf_drag-sheet1.png",
		"images/menu_utama-sheet0.png",
		"images/matahari-sheet0.png",
		"images/awan-sheet0.png",
		"images/nusantara-sheet0.png",
		"images/susunan-sheet0.png",
		"images/bermain-sheet0.png",
		"images/lanjut-sheet0.png",
		"images/hitam-sheet0.png",
		"images/sprite-sheet0.png",
		"images/particles.png",
		"images/bg2-sheet0.png",
		"images/kotak2-sheet0.png",
		"images/kotak3-sheet0.png",
		"images/bermain2-sheet0.png",
		"images/bghitam-sheet0.png",
		"images/bg3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/character-sheet0.png",
		"images/gameover-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/loadbar-sheet0.png",
		"images/stiker-sheet0.png",
		"images/kemendikbud-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/mame-sheet0.png",
		"images/universitasteknokrat-sheet0.png",
		"images/logorumahbelajar-sheet0.png",
		"images/info-sheet0.png",
		"media/bali.ogg",
		"media/jakarta.ogg",
		"media/sumatra barat.ogg",
		"media/ampera palembang.ogg",
		"media/borobudur jateng.ogg",
		"media/gedugn sate bandung.ogg",
		"media/jam gadang padang.ogg",
		"media/monas jakarta.ogg",
		"media/siger lampung.ogg",
		"media/pure bali.ogg",
		"media/1.ogg",
		"media/10.ogg",
		"media/11.ogg",
		"media/12.ogg",
		"media/13.ogg",
		"media/14.ogg",
		"media/16.ogg",
		"media/17.ogg",
		"media/18.ogg",
		"media/19.ogg",
		"media/20.ogg",
		"media/2.ogg",
		"media/21.ogg",
		"media/22.ogg",
		"media/23.ogg",
		"media/24.ogg",
		"media/25.ogg",
		"media/26.ogg",
		"media/3.ogg",
		"media/4.ogg",
		"media/5.ogg",
		"media/6.ogg",
		"media/7.ogg",
		"media/8.ogg",
		"media/9.ogg",
		"media/15.ogg",
		"media/partikel.ogg",
		"media/perpindahan button level dll.ogg",
		"media/perpindahan puzle kembali ketempat semula.ogg",
		"media/mantep.ogg",
		"media/benar.ogg",
		"media/salah.ogg",
		"media/scroll lavel up.ogg",
		"media/backsound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}